[package]
name = "calc_dlmm"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = "0.2.100"
alloy-primitives = { version = "0.8.21", features = ["serde"] }

[lib]
crate-type = ["cdylib"]
